export const DATA = [ { categoryTitle: 'Comedies',
    categoryFilter: 'comedy',
    movies: 
     [ { id: '0d8DbGTAu9HZK4OAWldb',
         title: 'Land of Soap and Glory',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FpBsO9AZ.jpg?alt=media&token=2594d2c8-8844-4fff-a0c0-f74cc812573e',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: '9rfB1tOTdPOdKflTClI5',
         title: 'Under the Moon',
         description: 'A long description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F2cIhbCl.jpg?alt=media&token=3679b7d0-3b9e-43f9-b403-a9f8f1a8471c',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'I6OHocE6RtLoiEi0b63U',
         title: 'Eve',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FsW3BOsK.jpg?alt=media&token=981dd955-eec7-4356-acd5-801326abdf49',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'PaSdnkZMdQ8kV5H5A1Wx',
         title: 'Obsession',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FbXQ933a.jpg?alt=media&token=8140a9d9-dc13-4bf2-b871-54f3fb517846',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'VW2106ZV6G5uJofAKRHz',
         title: 'Ordinary Man',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F5sPPIKZ.jpg?alt=media&token=afcebdba-35ef-449e-9971-18b6781aaf65',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'WTyQ544AVYs7N3RXSmCx',
         title: 'G-Rated',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FbK2gL0z.jpg?alt=media&token=3a391902-f101-48c5-ae64-25cc8f95b3a8',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'YUxucI5DLHHNL53iC9XH',
         title: 'House Cat',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FMyLUu2Q.jpg?alt=media&token=5a0e8eeb-b757-4843-a90c-c3602e811037',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'ZbOa8zOoSBjnl3FXw9sZ',
         title: 'One Manhattan Day',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FBFw7ng1.jpg?alt=media&token=6d014a93-adb5-41e3-a7ce-02c976758c48',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'bqEAMDlibif7TJQoJjq8',
         title: 'How To Blow Up The World',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FteOHGD1.jpg?alt=media&token=29bbc525-1dba-44b8-9768-cf7c9457256f',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'gKfV95aT8lXZ1bmm8iDj',
         title: 'Finding You',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FdRPf7li.jpg?alt=media&token=6602f611-137d-4e0e-8bfd-d1d8d3d7fe3d',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' } ] },
  { categoryTitle: 'Horror',
    categoryFilter: 'horror',
    movies: 
     [ { id: 'V4qN1JENeoGSFvkwXdRS',
         title: 'Undying',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FMHFenoz.jpg?alt=media&token=a5e94f78-d9ed-4f1b-a931-4c00100801c5',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'Zs805aZDTMxtx7iBP9qF',
         title: 'House of Eyes',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FlSRgbB0.jpg?alt=media&token=cb83aefc-6186-4656-9db6-6d38d44f6cf6',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'xum3zf31oJOmSDkCcNzZ',
         title: 'I Am Here',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FogyALLq.jpg?alt=media&token=36dcf9cd-5339-4b1c-9b54-ace35c3f80de',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' } ] },
  { categoryTitle: 'Epic & Historical',
    categoryFilter: 'history',
    movies: 
     [ { id: '7OD4sdzfDSqsN3DoADHW',
         title: 'The Protectors: Fight for the West',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FLnv8gLg.jpg?alt=media&token=7f20c330-8d58-4d62-b1d4-2bb422e5784a',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'b6SgoAieimIA0JEZPzxd',
         title: 'X Axis',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FnLojsPB.jpg?alt=media&token=3a7d82f1-437c-42a2-a4f8-166d761fce51',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'hjqmm3ZjqrSr8KgT6COQ',
         title: 'The Protectors: Fight For the East',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FwA3l7hZ.jpg?alt=media&token=aa6e4404-ddd7-4a57-8cee-d67ff5f5bf5e',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'tbfe2oKqIEoxr5SHfkXN',
         title: 'The Protectors: Fight for the North',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FNF6lEaU.jpg?alt=media&token=794341e1-45be-48fd-b7b9-c6da653402bb',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'vuK5ftYuEanDwFn8XEUp',
         title: 'The Protectors',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FDlJXr17.jpg?alt=media&token=6cf1b274-8c94-4f1a-9ee8-0529f57597b2',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'yKNpHr4ZJTIPEzgp4JnE',
         title: 'Interstellar 2',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FAjuU7kU.jpg?alt=media&token=65f1881f-1196-448a-ad81-847db31581fc',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' } ] },
  { categoryTitle: 'Science Fiction ',
    categoryFilter: 'science_fiction',
    movies: 
     [ { id: '9rfB1tOTdPOdKflTClI5',
         title: 'Under the Moon',
         description: 'A long description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F2cIhbCl.jpg?alt=media&token=3679b7d0-3b9e-43f9-b403-a9f8f1a8471c',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'GkVKKLQ7Nq68iMwucGrQ',
         title: 'Last Resort',
         description: 'A long description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F57W2T3n.jpg?alt=media&token=405ca89f-7d64-45ca-a6a0-b7d974a4b666',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'IJW29dltKrxZjAUff4vy',
         title: 'Last Man Standing',
         description: 'A man happens to be the last man standing',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F35FqEP1.jpg?alt=media&token=4e583b65-48dc-450a-ab31-eb01b1bcde5d',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'Kz6TWbWtXVXhByWTOZ3m',
         title: 'Miniland',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FVggDSCI.jpg?alt=media&token=157344ca-038c-4c6e-bd23-5fd6ae8714f2',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'WTyQ544AVYs7N3RXSmCx',
         title: 'G-Rated',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FbK2gL0z.jpg?alt=media&token=3a391902-f101-48c5-ae64-25cc8f95b3a8',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'a6HSsfzYog7AfgzuCgKY',
         title: 'Potential For Life',
         description: 'A longer Description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FqdVKzB9.jpg?alt=media&token=7bcbeaf7-f10e-4082-bc5a-30b55f9821e0',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'uc1lT7nayv9GYNP6t8zC',
         title: 'Totem',
         description: 'A long description about this movie',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F24ZfAGF.jpg?alt=media&token=09d5b080-6e1b-4c10-83f9-2c76aa37a42b',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' } ] },
  { categoryTitle: 'Romantic',
    categoryFilter: 'romance',
    movies: 
     [ { id: '8SOreWrNlWKCmahWoXzC',
         title: 'Right On Time',
         description: 'Longer description about this movie',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F0AQaMOh.jpg?alt=media&token=0d8bcd93-b11d-4dff-b608-003ce18f5673',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'gKfV95aT8lXZ1bmm8iDj',
         title: 'Finding You',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FdRPf7li.jpg?alt=media&token=6602f611-137d-4e0e-8bfd-d1d8d3d7fe3d',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' } ] },
  { categoryTitle: 'Dramas',
    categoryFilter: 'drama',
    movies: 
     [ { id: '8SOreWrNlWKCmahWoXzC',
         title: 'Right On Time',
         description: 'Longer description about this movie',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F0AQaMOh.jpg?alt=media&token=0d8bcd93-b11d-4dff-b608-003ce18f5673',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'GkVKKLQ7Nq68iMwucGrQ',
         title: 'Last Resort',
         description: 'A long description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F57W2T3n.jpg?alt=media&token=405ca89f-7d64-45ca-a6a0-b7d974a4b666',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'I6OHocE6RtLoiEi0b63U',
         title: 'Eve',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FsW3BOsK.jpg?alt=media&token=981dd955-eec7-4356-acd5-801326abdf49',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'IJW29dltKrxZjAUff4vy',
         title: 'Last Man Standing',
         description: 'A man happens to be the last man standing',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F35FqEP1.jpg?alt=media&token=4e583b65-48dc-450a-ab31-eb01b1bcde5d',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'K4oD3toiBAV9RoKkFasT',
         title: 'Stormfront',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FF2jXhdl.jpg?alt=media&token=95627cf1-557e-4839-afc3-c284604de154',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'Kz6TWbWtXVXhByWTOZ3m',
         title: 'Miniland',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FVggDSCI.jpg?alt=media&token=157344ca-038c-4c6e-bd23-5fd6ae8714f2',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'V4qN1JENeoGSFvkwXdRS',
         title: 'Undying',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FMHFenoz.jpg?alt=media&token=a5e94f78-d9ed-4f1b-a931-4c00100801c5',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'h6r6mOoKSggRFYQ02OpI',
         title: 'Ellevation',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FMBqNkKQ.jpg?alt=media&token=1db09f14-0fbd-4804-8de4-85c2a829b01b',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'uc1lT7nayv9GYNP6t8zC',
         title: 'Totem',
         description: 'A long description about this movie',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F24ZfAGF.jpg?alt=media&token=09d5b080-6e1b-4c10-83f9-2c76aa37a42b',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'yKNpHr4ZJTIPEzgp4JnE',
         title: 'Interstellar 2',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FAjuU7kU.jpg?alt=media&token=65f1881f-1196-448a-ad81-847db31581fc',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' } ] },
  { categoryTitle: 'True Crime',
    categoryFilter: 'crime',
    movies: 
     [ { id: 'PaSdnkZMdQ8kV5H5A1Wx',
         title: 'Obsession',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FbXQ933a.jpg?alt=media&token=8140a9d9-dc13-4bf2-b871-54f3fb517846',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'SIYpvh6ELl59WYWOZGbn',
         title: 'Under Control',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2F2OPj6SI.jpg?alt=media&token=54e01ad4-a8fd-4217-abaa-2a3b9c9267a4',
         video: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8' },
       { id: 'YQ8LOgwoGa1wFvGDhFXG',
         title: 'Waves',
         description: 'A longer description',
         image: 'https://firebasestorage.googleapis.com/v0/b/sample-movie-api.appspot.com/o/posters%2FPq90Iwb.jpg?alt=media&token=752e73d0-8523-455c-87d1-00a00bbb07ca' } ] } ]